import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: process.env.CHROME || undefined, args:['--no-sandbox','--disable-dev-shm-usage'] });
const page = await b.newPage({ viewport:{ width:1440, height:960 }, deviceScaleFactor:1 });
const errs=[]; page.on('pageerror', e=>errs.push('PAGEERROR '+e.message)); page.on('console', m=>{ if(m.type()==='error') errs.push('CONSOLE '+m.text()); });
await page.goto('file:///home/user/index.html');
await page.waitForTimeout(700);
await page.screenshot({ path:'/home/user/shots/01-login.png' });
await page.click('[data-demo-login]');
await page.waitForTimeout(1600);
await page.screenshot({ path:'/home/user/shots/02-board.png', fullPage:false });
await page.click('[data-nav="demo"]'); await page.waitForTimeout(1200);
await page.screenshot({ path:'/home/user/shots/03-demo.png' });
await page.fill('[data-form="bot"] input[name="text"]','Здравствуйте! Нужен счёт на предоплату по договору №441');
await page.press('[data-form="bot"] input[name="text"]','Enter');
await page.waitForTimeout(2600);
await page.screenshot({ path:'/home/user/shots/04-pipeline.png' });
await page.waitForTimeout(3200);
await page.click('[data-nav="analytics"]'); await page.waitForTimeout(1600);
await page.screenshot({ path:'/home/user/shots/05-analytics.png' });
await page.click('[data-nav="board"]'); await page.waitForTimeout(1400);
await page.click('.tcard'); await page.waitForTimeout(1400);
await page.screenshot({ path:'/home/user/shots/06-task.png' });
await page.keyboard.press('Escape'); await page.waitForTimeout(400);
await page.click('[data-nav="employees"]'); await page.waitForTimeout(1300);
await page.screenshot({ path:'/home/user/shots/07-employees.png' });
await page.click('[data-nav="settings"]'); await page.waitForTimeout(1400);
await page.click('[data-act="settings-tab"][data-tab="sec"]'); await page.waitForTimeout(600);
await page.screenshot({ path:'/home/user/shots/08-settings.png' });
// dark theme
await page.click('[data-act="theme"]'); await page.waitForTimeout(500);
await page.click('[data-nav="board"]'); await page.waitForTimeout(1300);
await page.screenshot({ path:'/home/user/shots/09-dark.png' });
await page.click('[data-act="theme"]'); await page.waitForTimeout(400);
// mobile
const m = await b.newPage({ viewport:{ width:390, height:844 }, isMobile:true, hasTouch:true });
await m.goto('file:///home/user/index.html'); await m.waitForTimeout(600);
await m.click('[data-demo-login]'); await m.waitForTimeout(1800);
await m.screenshot({ path:'/home/user/shots/10-mobile.png' });
await m.click('[data-act="nav-toggle"]'); await m.waitForTimeout(500);
await m.screenshot({ path:'/home/user/shots/11-mobile-nav.png' });
console.log('errors:', errs.length); errs.slice(0,10).forEach(e=>console.log('* '+e));
await b.close();
